services:
  vllm-server:
    image: vllm/vllm-openai:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data:/english-handwritten/data
    command: --model /english-handwritten/data/models/gemma-3-12b-it --dtype bfloat16 --tensor-parallel-size 4 --host 0.0.0.0 --port 8001
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  airflow-webserver:
    image: apache/airflow:2.8.1
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
      - ./data:/english-handwritten/data
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    command: >
      bash -c "
        airflow db init || true
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true
        airflow webserver
      "

  extractor:
    build: ./data
    volumes:
      - ./data:/english-handwritten/data
    command: sleep infinity